// ============================================================
// GuardRAIL – Overview Page
// ============================================================
import {
  AlertTriangle, Lock, Cpu, GitPullRequest, Clock, CheckCircle2,
  Server, BookOpen, TrendingUp, Activity, ShieldAlert, ArrowRight
} from 'lucide-react';
import {
  AreaChart, Area, PieChart, Pie, Cell, BarChart, Bar,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, Legend
} from 'recharts';
import { useNavigate } from 'react-router-dom';
import { useAppStore } from '../store/appStore';
import { DEMO_STATS, SEVERITY_CHART_DATA, TIMELINE_CHART_DATA, CATEGORY_CHART_DATA, REMEDIATION_TIME_DATA } from '../data/demoData';
import { StatCard, SeverityBadge, StatusBadge } from '../components/ui';
import { DemoRunner } from '../components/DemoRunner';
import { formatRelativeTime } from '../utils';

const CHART_COLORS = { grid: '#1f2937', tick: '#475569' };

function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: { value: number; name: string; color: string }[]; label?: string }) {
  if (!active || !payload?.length) return null;
  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)', borderRadius: 8, padding: '10px 14px', fontSize: '0.8rem' }}>
      <div style={{ color: 'var(--text-muted)', marginBottom: 6 }}>{label}</div>
      {payload.map(p => (
        <div key={p.name} style={{ color: p.color, marginBottom: 2 }}>
          {p.name}: <strong>{p.value}</strong>
        </div>
      ))}
    </div>
  );
}

export default function OverviewPage() {
  const { incidents, auditEvents } = useAppStore();
  const navigate = useNavigate();

  const recentActivity = auditEvents.slice(0, 8);

  const actorColor = (type: string) => ({ human: 'var(--accent)', ai: 'var(--purple)', system: 'var(--text-muted)' }[type] ?? 'var(--text-muted)');

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 1400 }} className="animate-fade-in">

      {/* Demo Runner */}
      <DemoRunner />

      {/* Stats Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 16 }}>
        <StatCard title="TOTAL FINDINGS" value={DEMO_STATS.totalFindings} icon={<BookOpen size={18} />} subtitle="All-time findings" delta="+3" deltaUp={false} gradient="linear-gradient(135deg, #06b6d4, #8b5cf6)" />
        <StatCard title="CRITICAL" value={DEMO_STATS.criticalVulnerabilities} icon={<AlertTriangle size={18} />} color="var(--critical)" subtitle="Immediate action required" delta="+2" deltaUp={false} />
        <StatCard title="QUARANTINED" value={DEMO_STATS.resourcesQuarantined} icon={<Lock size={18} />} color="var(--high)" subtitle="Resources contained" />
        <StatCard title="AI PATCHES" value={DEMO_STATS.aiPatchesGenerated} icon={<Cpu size={18} />} color="var(--purple)" subtitle="Generated by Bedrock" />
        <StatCard title="AWAITING APPROVAL" value={DEMO_STATS.prAwaitingApproval} icon={<GitPullRequest size={18} />} color="var(--medium)" subtitle="PRs pending review" />
        <StatCard title="MEAN REMEDIATION" value={DEMO_STATS.meanRemediationTime} icon={<Clock size={18} />} color="var(--accent)" subtitle="Detection to fix" />
        <StatCard title="RESOLVED" value={DEMO_STATS.resolvedIncidents} icon={<CheckCircle2 size={18} />} color="var(--resolved)" subtitle="Incidents closed" />
        <StatCard title="REPOSITORIES" value={DEMO_STATS.connectedRepositories} icon={<Server size={18} />} subtitle="GitHub repos monitored" />
      </div>

      {/* Charts row 1 */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16 }}>
        {/* Findings over time */}
        <div className="card" style={{ padding: 20, gridColumn: 'span 2' }}>
          <div style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: 16, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <Activity size={16} color="var(--accent)" /> Vulnerabilities Detected Over Time
          </div>
          <ResponsiveContainer width="100%" height={200}>
            <AreaChart data={TIMELINE_CHART_DATA}>
              <defs>
                <linearGradient id="grad-detect" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#ef4444" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="#ef4444" stopOpacity={0} />
                </linearGradient>
                <linearGradient id="grad-resolve" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#22c55e" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="#22c55e" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke={CHART_COLORS.grid} />
              <XAxis dataKey="date" tick={{ fill: CHART_COLORS.tick, fontSize: 11 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: CHART_COLORS.tick, fontSize: 11 }} axisLine={false} tickLine={false} />
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: '0.78rem', color: 'var(--text-muted)' }} />
              <Area type="monotone" dataKey="detected" name="Detected" stroke="#ef4444" fill="url(#grad-detect)" strokeWidth={2} />
              <Area type="monotone" dataKey="resolved" name="Resolved" stroke="#22c55e" fill="url(#grad-resolve)" strokeWidth={2} />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        {/* Severity donut */}
        <div className="card" style={{ padding: 20 }}>
          <div style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: 16, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <ShieldAlert size={16} color="var(--accent)" /> Findings by Severity
          </div>
          <ResponsiveContainer width="100%" height={160}>
            <PieChart>
              <Pie data={SEVERITY_CHART_DATA} cx="50%" cy="50%" innerRadius={45} outerRadius={70} paddingAngle={3} dataKey="value">
                {SEVERITY_CHART_DATA.map((entry, i) => <Cell key={i} fill={entry.fill} />)}
              </Pie>
              <Tooltip formatter={(v, n) => [v, n]} contentStyle={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)', borderRadius: 8, fontSize: '0.8rem' }} />
            </PieChart>
          </ResponsiveContainer>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px 16px', justifyContent: 'center' }}>
            {SEVERITY_CHART_DATA.map(d => (
              <div key={d.name} style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                <div style={{ width: 8, height: 8, borderRadius: '50%', background: d.fill }} />
                {d.name} ({d.value})
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Charts row 2 */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        {/* Category bar */}
        <div className="card" style={{ padding: 20 }}>
          <div style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: 16, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <TrendingUp size={16} color="var(--accent)" /> Findings by Category
          </div>
          <ResponsiveContainer width="100%" height={180}>
            <BarChart data={CATEGORY_CHART_DATA} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke={CHART_COLORS.grid} horizontal={false} />
              <XAxis type="number" tick={{ fill: CHART_COLORS.tick, fontSize: 11 }} axisLine={false} tickLine={false} />
              <YAxis type="category" dataKey="name" tick={{ fill: CHART_COLORS.tick, fontSize: 10 }} axisLine={false} tickLine={false} width={110} />
              <Tooltip contentStyle={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)', borderRadius: 8, fontSize: '0.8rem' }} />
              <Bar dataKey="count" name="Findings" radius={[0, 4, 4, 0]}>
                {CATEGORY_CHART_DATA.map((d, i) => <Cell key={i} fill={d.fill} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Remediation time */}
        <div className="card" style={{ padding: 20 }}>
          <div style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: 16, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <Clock size={16} color="var(--accent)" /> Avg Detection & Remediation Time (min)
          </div>
          <ResponsiveContainer width="100%" height={180}>
            <LineChart data={REMEDIATION_TIME_DATA}>
              <CartesianGrid strokeDasharray="3 3" stroke={CHART_COLORS.grid} />
              <XAxis dataKey="date" tick={{ fill: CHART_COLORS.tick, fontSize: 11 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: CHART_COLORS.tick, fontSize: 11 }} axisLine={false} tickLine={false} />
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: '0.78rem', color: 'var(--text-muted)' }} />
              <Line type="monotone" dataKey="detect" name="Detection (min)" stroke="#06b6d4" strokeWidth={2} dot={false} />
              <Line type="monotone" dataKey="remediate" name="Remediation (min)" stroke="#8b5cf6" strokeWidth={2} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Bottom: Recent incidents + Activity feed */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 380px', gap: 16 }}>
        {/* Recent incidents */}
        <div className="card" style={{ padding: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
            <div style={{ fontWeight: 600, fontSize: '0.9rem', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
              <AlertTriangle size={16} color="var(--accent)" /> Recent Incidents
            </div>
            <button className="btn btn-ghost btn-sm" onClick={() => navigate('/incidents')}>
              View all <ArrowRight size={13} />
            </button>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {incidents.slice(0, 4).map(inc => (
              <div
                key={inc.incidentId}
                onClick={() => navigate(`/incidents/${inc.incidentId}`)}
                style={{
                  padding: '12px 14px',
                  borderRadius: 10, cursor: 'pointer',
                  border: '1px solid var(--border-subtle)',
                  background: 'var(--bg-elevated)',
                  display: 'flex', alignItems: 'center', gap: 12,
                  transition: 'all 0.15s',
                }}
                className="hover:border-[var(--border-default)] hover:bg-[var(--bg-card-hover)]"
              >
                <SeverityBadge severity={inc.severity} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-primary)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {inc.title}
                  </div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: 2 }}>
                    {inc.repository} · {inc.filePath}
                  </div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4, flexShrink: 0 }}>
                  <StatusBadge status={inc.status} />
                  <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{formatRelativeTime(inc.detectedAt)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Activity timeline */}
        <div className="card" style={{ padding: 20 }}>
          <div style={{ fontWeight: 600, fontSize: '0.9rem', color: 'var(--text-primary)', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
            <Activity size={16} color="var(--accent)" /> Activity Feed
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
            {recentActivity.map((evt, i) => (
              <div key={evt.eventId} style={{ display: 'flex', gap: 12, paddingBottom: 14, position: 'relative' }}>
                {i < recentActivity.length - 1 && (
                  <div style={{ position: 'absolute', left: 15, top: 28, bottom: 0, width: 1, background: 'var(--border-subtle)' }} />
                )}
                <div style={{
                  width: 30, height: 30, borderRadius: '50%', flexShrink: 0,
                  background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '0.65rem', fontWeight: 700, color: actorColor(evt.actorType),
                }}>
                  {evt.actorType === 'human' ? 'H' : evt.actorType === 'ai' ? 'AI' : 'S'}
                </div>
                <div style={{ flex: 1, minWidth: 0, paddingTop: 4 }}>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', fontWeight: 500 }}>
                    <span style={{ color: actorColor(evt.actorType), fontFamily: 'JetBrains Mono, monospace', fontSize: '0.72rem' }}>
                      {evt.action}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: 2 }}>
                    {evt.actor.split('-').slice(0, 2).join(' ')}
                    {evt.incidentId && ` · ${evt.incidentId}`}
                  </div>
                  <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: 1 }}>
                    {formatRelativeTime(evt.timestamp)}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
