// ============================================================
// GuardRAIL – Pull Requests Page
// ============================================================
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  GitPullRequest, ExternalLink, CheckCircle2, Clock,
  Filter, ArrowUpRight, GitMerge, ShieldCheck
} from 'lucide-react';
import { DEMO_PULL_REQUESTS } from '../data/demoData';
import { SeverityBadge, SectionHeader } from '../components/ui';
import { formatRelativeTime } from '../utils';

export default function PullRequestsPage() {
  const navigate = useNavigate();
  const [filter, setFilter] = useState<'all' | 'open' | 'merged'>('all');

  const filtered = DEMO_PULL_REQUESTS.filter(pr => {
    if (filter === 'all') return true;
    return pr.status === filter;
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20, maxWidth: 1200 }} className="animate-fade-in">
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}>
        <SectionHeader
          title="Automated Pull Requests"
          subtitle="Remediation patches generated by Bedrock AI and submitted to GitHub"
        />

        <div style={{ display: 'flex', gap: 8, background: 'var(--bg-card)', padding: 4, borderRadius: 8, border: '1px solid var(--border-subtle)' }}>
          {(['all', 'open', 'merged'] as const).map(tab => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              style={{
                padding: '6px 14px',
                borderRadius: 6,
                fontSize: '0.8rem',
                fontWeight: 500,
                textTransform: 'capitalize',
                background: filter === tab ? 'var(--accent-dim)' : 'transparent',
                color: filter === tab ? 'var(--accent)' : 'var(--text-secondary)',
                border: filter === tab ? '1px solid var(--accent-border)' : '1px solid transparent',
                cursor: 'pointer',
                transition: 'all 0.15s'
              }}
            >
              {tab} ({DEMO_PULL_REQUESTS.filter(p => tab === 'all' || p.status === tab).length})
            </button>
          ))}
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {filtered.map(pr => (
          <div
            key={pr.prId}
            className="card"
            style={{
              padding: '18px 20px',
              display: 'flex',
              flexDirection: 'column',
              gap: 12,
              transition: 'border-color 0.15s',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                <div
                  style={{
                    width: 36,
                    height: 36,
                    borderRadius: 8,
                    background: pr.status === 'merged' ? 'rgba(139, 92, 246, 0.15)' : 'rgba(34, 197, 94, 0.15)',
                    border: `1px solid ${pr.status === 'merged' ? 'rgba(139, 92, 246, 0.3)' : 'rgba(34, 197, 94, 0.3)'}`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    marginTop: 2
                  }}
                >
                  {pr.status === 'merged' ? (
                    <GitMerge size={18} color="#a855f7" />
                  ) : (
                    <GitPullRequest size={18} color="#22c55e" />
                  )}
                </div>

                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 4 }}>
                    <span style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)' }}>
                      #{pr.number}
                    </span>
                    <span style={{ fontSize: '0.92rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                      {pr.title}
                    </span>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                    <span>Repo: <strong style={{ color: 'var(--text-secondary)' }}>{pr.repository}</strong></span>
                    <span>•</span>
                    <span>Branch: <code style={{ color: 'var(--accent)' }}>{pr.branch}</code> → <code>{pr.targetBranch}</code></span>
                    <span>•</span>
                    <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                      <Clock size={12} /> {formatRelativeTime(pr.createdAt)}
                    </span>
                  </div>
                </div>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <SeverityBadge severity={pr.severity} />
                <span
                  style={{
                    fontSize: '0.72rem',
                    fontWeight: 600,
                    padding: '3px 8px',
                    borderRadius: 4,
                    textTransform: 'uppercase',
                    background: pr.status === 'merged' ? 'rgba(139, 92, 246, 0.15)' : 'rgba(34, 197, 94, 0.15)',
                    color: pr.status === 'merged' ? '#a855f7' : '#22c55e',
                    border: `1px solid ${pr.status === 'merged' ? 'rgba(139, 92, 246, 0.3)' : 'rgba(34, 197, 94, 0.3)'}`
                  }}
                >
                  {pr.status}
                </span>
              </div>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingTop: 10, borderTop: '1px solid var(--border-subtle)', flexWrap: 'wrap' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: '0.75rem', color: 'var(--resolved)', marginRight: 8 }}>
                  <ShieldCheck size={14} /> Checks: {pr.validationStatus}
                </span>
                {pr.labels.map(l => (
                  <span
                    key={l}
                    style={{
                      fontSize: '0.7rem',
                      padding: '2px 8px',
                      borderRadius: 12,
                      background: 'var(--bg-surface)',
                      color: 'var(--text-secondary)',
                      border: '1px solid var(--border-subtle)'
                    }}
                  >
                    {l}
                  </span>
                ))}
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <button
                  className="btn btn-secondary"
                  style={{ fontSize: '0.78rem', padding: '5px 12px' }}
                  onClick={() => navigate(`/incidents/${pr.incidentId}`)}
                >
                  View Incident ({pr.incidentId})
                </button>
                <a
                  href={pr.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-ghost"
                  style={{ fontSize: '0.78rem', padding: '5px 12px', display: 'flex', alignItems: 'center', gap: 4 }}
                >
                  GitHub PR <ExternalLink size={13} />
                </a>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
